config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('blog/', include('blogapp.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]

myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='main'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('client_page/<int:pk>/', views.ClientView.as_view(), name='client_page'),
    path('product_page/<int:pk>/', views.ProductView.as_view(), name='product_page'),
    path('orders/year/<int:year>/<int:pk>/', views.AllYearProductsView.as_view(), name='orders_year'),
    path('orders/month/<int:year>/<int:month>/<int:pk>/', views.AllYearProductsView.as_view(), name='orders_month'),
    path('orders/week/<int:year>/<int:month>/<int:week>/<int:pk>/',
         views.AllYearProductsView.as_view(), name='orders_week'),
    path('update_product/<int:pk>/', views.UpdateProductView.as_view(), name='update_product'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp_3.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp_3.urls')),
    path('les3/', include('myapp_3.urls')),
    path('', index),
    path('les4/', include('myapp_4.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
    path('les6/', include('myapp_6.urls')),
]

myapp/models.py
from django.db import models
from django.db.models import Manager
from django.urls import reverse


class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=100)
    registered_date = models.DateField(auto_now_add=True)
    objects = Manager()

    def __str__(self):
        return f'Name client: {self.name}, email: {self.email}, registered_date: {self.registered_date}'


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    objects = Manager()

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField(default='', blank=True)
    price = models.DecimalField(default=999999.99, max_digits=8, decimal_places=2)
    count = models.PositiveSmallIntegerField(default=0)
    added_date = models.DateField(auto_now_add=True)
    rating = models.DecimalField(default=5.0, max_digits=3, decimal_places=2)
    image = models.ImageField(upload_to='media/product_images',
                              default='default.png',
                              verbose_name='product_image')
    objects = Manager()

    def get_absolute_url(self):
        return reverse('myapp:product_page', kwargs={'pk': self.pk})

    def __str__(self):
        return f'Product: {self.title}, price: {self.price}, added_date: {self.added_date}'


class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    registered_order_date = models.DateField(auto_now_add=True)
    objects = Manager()

    def __str__(self):
        return (f'Client`s {self.client} order: {self.product},'
                f'amount: {self.amount},'
                f'registered_order_date: {self.registered_order_date}')

myapp/forms.py
from django import forms

from .models import Product


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'count', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'count': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }

myapp/views.py
import logging

from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, UpdateView
from datetime import datetime
from django.views.generic.dates import YearArchiveView, MonthArchiveView, WeekArchiveView, ArchiveIndexView
from myapp import models, forms

logger = logging.getLogger(__name__)


class MainPageView(TemplateView):
    logger.info('index.html accessed!')
    template_name = 'myapp/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Main'
        return context


class AboutPageView(TemplateView):
    logger.info('about.html accessed!')
    template_name = 'myapp/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'About'
        return context


class ClientView(DetailView):
    model = models.Client
    template_name = 'myapp/client_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_date'] = datetime.now()
        return context


class AllProductsView(ArchiveIndexView):
    model = models.Order
    date_field = 'registered_order_date'
    template_name = 'myapp/client_products.html'
    allow_future = False
    week_format = '%U'
    year_format = '%Y'

    def get_context_data(self, **kwargs):
        client = models.Client.objects.get(pk=self.kwargs.get('pk'))
        orders = super().get_queryset().filter(client=client).prefetch_related('product')
        product = set(product for order in orders for product in order.product.values_list('title'))

        context = super().get_context_data(**kwargs)
        context['product'] = product
        context['client'] = client

        return context

    def get_queryset(self, **kwargs):
        orders = models.Order.objects.get_queryset().filter(client=self.kwargs.get('pk'))

        return orders


class AllYearProductsView(AllProductsView, YearArchiveView):
    pass


class AllMonthProductsView(AllProductsView, MonthArchiveView):
    pass


class AllWeekProductsView(AllProductsView, WeekArchiveView):
    pass


class ProductView(DetailView):
    model = models.Product
    template_name = 'myapp/product_page.html'


class UpdateProductView(UpdateView):
    model = models.Product
    template_name = 'myapp/update_product.html'
    form_class = forms.ProductUpdateForm

myapp/templates/myapp/about.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <h1>Обо мне</h1>
    <p>Инженер-энергетик</p>
    <p><a href="{% url 'myapp:main' %}">Назад на главную страницу</a></p>
{% endblock %}

myapp/templates/myapp/client_page.html
{% extends 'base.html' %}

{% block content %}
    <h1>Client: {{ client }}</h1>

    <p>Посмотреть заказы:</p>
    <a href="{% url 'myapp:orders_year' year=current_date|date:'Y' pk=client.pk %}">За год</a>
    <a href="{% url 'myapp:orders_month' year=current_date|date:'Y' month=current_date|date:'m' pk=client.pk %}">За
        месяц</a>
    <a href="{% url 'myapp:orders_week' year=current_date|date:'Y' month=current_date|date:'m'
    week=current_date|date:'W' pk=client.pk %}">За неделю</a>
{% endblock %}

myapp/templates/myapp/client_products.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ client }}</h1>
    {% for product in products %}
        {% for prod in product %}
        	<p>{{ prod }}</p>
        {% endfor %}
    {% endfor %}
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <h1>Главная страница</h1>
    <p>Первый Django-сайт</p>
    <p><a href="{% url 'myapp:about' %}">Узнать больше обо мне</a></p>
{% endblock %}

myapp/templates/myapp/orders.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
{{ client.name }}
<ul>
    {% for order in orders %}
        <li><a href="{% url 'order' order.pk %}">{{ order.product }}</a></li>
    {% endfor %}
</ul>
<p><a href="{% url 'main' %}">Назад на главную страницу</a></p>
{% endblock %}

myapp/templates/myapp/product_page.html
{% extends 'base.html' %}

{% block content %}
    <p>{{ product.title }}</p>
    <p>{{ product.description }}</p>
    <a href="{% url 'myapp:update_product' product.pk %}">Редактировать товар</a>
{% endblock %}

myapp/templates/myapp/update_product.html
{% extends 'base.html' %}

{% block content %}
    <h2>Редактирование товара</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Обновить</button>
        <a href="{% url 'myapp:product_page' product.pk %}">Отмена</a>
    </form>
{% endblock %}